org.gradle.jvmargs=-Xmx4048M
minecraft_version=1.21.7
supported_minecraft_version=1.21.7,1.21.8
enabled_platforms=fabric,neoforge
archives_base_name=chatplus
mod_id=chatplus
mod_version=2.8.0
mod_name=ChatPlus
mod_description=Minecraft chat improved.
mod_authors=ebicep
maven_group=com.ebicep
# https://www.curseforge.com/minecraft/mc-mods/architectury-api
architectury_version=17.0.6
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=1.21.7-57.0.0
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.7.0-beta
# https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge/files
kotlin_for_forge_version=5.8.0
# https://fabricmc.net/develop/
fabric_loader_version=0.16.9
fabric_api_version=0.128.1+1.21.7
# https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin
fabric_kotlin_version=1.13.4+kotlin.2.2.0
# https://github.com/TerraformersMC/ModMenu/wiki/API
# https://modrinth.com/mod/modmenu/versions
modmenu_version=15.0.0-beta.3
# https://linkie.shedaniel.dev/dependencies
cloth_config_version=19.0.147